class Ball{
    gravity=6;
    constructor(x,y,d)
    {
        this.x=x;
        this.y=y;
        this.d=d;
    }
    show()
    {
        stroke(255);
        fill(255);
        ellipse(this.x,this.y,this.d);
    }
    fallDown()
    {
        if(!(this.y>600))
        {
            this.y+=this.gravity;
        }
    }
    moveUp()
    {
           if(!(this.y<0))
           {
            this.y-=100;
           }
    }
}